{
    shop = {
        {text = "Деньги", sellPrice = 1, buyPrice = 1, minCount = 0, maxCount = 1024, fingerprint = {{dmg=0.0,id="customnpcs:npcMoney"}}, raw_name = {"item.npcmoney"}},
        {text = "Малахит", sellPrice = 30, minCount = 0, maxCount = 1024, fingerprint = {{dmg=0.0,id="dwcity:Malahit"}}, raw_name = {"dwcity:Malahit"}},

        --vanilla
        {text = "Алмаз", buyPrice = 0.4, minCount = 0, maxCount = 2048, fingerprint = {{dmg=0.0,id="minecraft:diamond"}}, raw_name = {"item.diamond"}},
        {text = "Уголь", buyPrice = 0.05, minCount = 0, maxCount = 2048, fingerprint = {{dmg=0.0,id="minecraft:coal"}}, raw_name = {"item.coal"}},
        {text = "Красная пыль", buyPrice = 0.05, minCount = 0, maxCount = 1024, fingerprint = {{id="minecraft:redstone",dmg=0.0}}, raw_name = {"item.redstone"}},
        {text = "Светопыль", buyPrice = 0.05, minCount = 0, maxCount = 1024, fingerprint = {{id="minecraft:glowstone_dust",dmg=0.0}}, raw_name = {"item.yellowdust"}},
        {text = "Кварц", buyPrice = 0.05, minCount = 0, maxCount = 1024, fingerprint = {{dmg=0.0,id="minecraft:quartz"}}, raw_name = {"item.netherquartz"}},
        {text = "Изумруд", buyPrice = 1, minCount = 0, maxCount = 512, fingerprint = {{id="minecraft:emerald",dmg=0.0}}, raw_name = {"item.emerald"}},
        {text = "Шерсть", buyPrice = 0.05, minCount = 0, maxCount = 1024, fingerprint = {{id="minecraft:wool",dmg=0.0}}, raw_name = {"tile.cloth.white"}},
        {text = "Кость", buyPrice = 0.2, minCount = 0, maxCount = 1024, fingerprint = {{id="minecraft:bone",dmg=0.0}}, raw_name = {"item.bone"}},
        {text = "Гнилая плоть", buyPrice = 0.05, minCount = 0, maxCount = 1024, fingerprint = {{id="minecraft:rotten_flesh",dmg=0.0}}, raw_name = {"item.rottenflesh"}},
        {text = "Жемчуг эндера", buyPrice = 0.4, minCount = 0, maxCount = 1024, fingerprint = {{id="minecraft:ender_pearl",dmg=0.0}}, raw_name = {"item.enderpearl"}},
        {text = "Череп скелета", buyPrice = 0.2, minCount = 0, maxCount = 256, fingerprint = {{id="minecraft:skull",dmg=0.0}}, raw_name = {"item.skull.skeleton"}},
        {text = "Голова зомби", buyPrice = 0.2, minCount = 0, maxCount = 256, fingerprint = {{id="minecraft:skull",dmg=2.0}}, raw_name = {"item.skull.zombie"}},
        {text = "Перо", buyPrice = 0.05, minCount = 0, maxCount = 1024, fingerprint = {{dmg=0.0,id="minecraft:feather"}}, raw_name = {"item.feather"}},
        {text = "Стержень ифрита", buyPrice = 0.5, minCount = 0, maxCount = 512, fingerprint = {{id="minecraft:blaze_rod",dmg=0.0}}, raw_name = {"item.blazerod"}},
        {text = "Сгусток слизи", buyPrice = 0.5, minCount = 0, maxCount = 512, fingerprint = {{id="minecraft:slime_ball",dmg=0.0}}, raw_name = {"item.slimeball"}},
        {text = "Слеза Гаста", buyPrice = 0.4, minCount = 0, maxCount = 512, fingerprint = {{id="minecraft:ghast_tear",dmg=0.0}}, raw_name = {"item.ghasttear"}},
        {text = "Адская звезда", buyPrice = 100, minCount = 0, maxCount = 32, fingerprint = {{id="minecraft:nether_star",dmg=0.0}}, raw_name = {"item.netherstar"}},
        {text = "Кожа", buyPrice = 0.2, minCount = 0, maxCount = 1024, fingerprint = {{id="minecraft:leather",dmg=0.0}}, raw_name = {"item.leather"}},
        {text = "Обсидиан", buyPrice = 0.05, minCount = 0, maxCount = 1024, fingerprint = {{id="minecraft:obsidian",dmg=0.0}}, raw_name = {"tile.obsidian"}},
        {text = "Сырая рыба", buyPrice = 0.1, minCount = 0, maxCount = 1024, fingerprint = {{id="minecraft:fish",dmg=0.0}}, raw_name = {"item.fish.cod.raw"}},
        {text = "Яйцо", buyPrice = 0.1, minCount = 0, maxCount = 1024, fingerprint = {{id="minecraft:egg",dmg=0.0}}, raw_name = {"item.egg"}},
        {text = "Сахарный тростник", buyPrice = 0.01, minCount = 0, maxCount = 2048, fingerprint = {{id="minecraft:reeds",dmg=0.0}}, raw_name = {"item.reeds"}},
        {text = "Череп Скелета-Иссушителя", buyPrice = 30, minCount = 0, needed = 128, maxCount = 128, fingerprint = {{dmg=1.0,id="minecraft:skull"}}, raw_name = {"item.skull.wither"}},


        --ae2
        {text = "Кристалл истинного кварца", buyPrice = 0.2, minCount = 0, maxCount = 2048, fingerprint = {{dmg=0.0,id="appliedenergistics2:item.ItemMultiMaterial"}}, raw_name = {"item.appliedenergistics2.itemmaterial.certusquartzcrystal"}},
        {text = "Череп Скелета-Иссушителя", buyPrice = 30, minCount = 0, needed = 128, maxCount = 128, fingerprint = {{dmg=1.0,id="minecraft:skull"}}, raw_name = {"item.skull.wither"}},
        {text = "Зар. кристалл ист. кварца", buyPrice = 0.5, minCount = 0, maxCount = 256, needed = 256, fingerprint = {{dmg=1.0,id="appliedenergistics2:item.ItemMultiMaterial"}}, raw_name = {"item.appliedenergistics2.itemmaterial.certusquartzcrystalcharged"}},
        {text = "Вычислительный пресс", buyPrice = 17, minCount = 0, maxCount = 2, needed = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=13.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.calcprocessorpress"}},
        {text = "Инженерный пресс", buyPrice = 17, minCount = 0, maxCount = 2, needed = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=14.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.engprocessorpress"}},
        {text = "Логический пресс", buyPrice = 17, minCount = 0, maxCount = 2, needed = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=15.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.logicprocessorpress"}},
        {text = "Кремниевый пресс", buyPrice = 17, minCount = 0, maxCount = 2, needed = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=19.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.siliconpress"}},
        {text = "Сингулярность", buyPrice = 10, minCount = 0, maxCount = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=47.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.singularity"}},
        {text = "Небесный камень", buyPrice = 0.15, minCount = 0, maxCount = 2048, fingerprint = {{id="appliedenergistics2:tile.BlockSkyStone",dmg=0.0}}, raw_name = {"tile.appliedenergistics2.blockskystone"}},
        {text = "Логический процессор", buyPrice = 0.15, minCount = 0, maxCount = 512, needed = 512, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=22.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.logicprocessor"}},
        {text = "Инженерный процессор", buyPrice = 0.45, minCount = 0, maxCount = 512, needed = 512, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=24.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.engprocessor"}},
        {text = "Вычислительный процессор", buyPrice = 0.25, minCount = 0, maxCount = 512, needed = 512, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=23.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.calcprocessor"}},
        {text="Изменчивый кристалл",maxCount="512",fingerprint={{dmg=7.0,id="appliedenergistics2:item.ItemMultiMaterial"}},minCount=0,raw_name={"item.appliedenergistics2.itemmaterial.fluixcrystal"},buyPrice="0.2"},
        {text="МЭ умный кабель",maxCount="512", needed=512, fingerprint={{dmg=56.0,id="appliedenergistics2:item.ItemMultiPart"}},minCount=0,raw_name={"item.appliedenergistics2.itempart.cablesmart"},buyPrice="0.05"},
        {text="МЭ плотный кабель",maxCount="256", needed=256,fingerprint={{dmg=76.0,id="appliedenergistics2:item.ItemMultiPart"}},minCount=0,raw_name={"item.appliedenergistics2.itempart.cabledense"},buyPrice="0.3"},
        {text="Улучшенный МЭ интерфейс",maxCount="32", needed=32,fingerprint={{dmg=0.0,id="dwcity:blockAdvancedInterface"}},minCount=0,raw_name={"tile.advanced_interface"},buyPrice="2.00"},
        {text="Гибридный МЭ интерфейс",maxCount="32", needed=32,fingerprint={{dmg=0.0,id="dwcity:blockHybridInterface"}},minCount=0,raw_name={"tile.hybrid_interface"},buyPrice="5"},
        {text="Совершенный МЭ интерфейс",maxCount="32", needed=32,fingerprint={{dmg=0.0,id="dwcity:blockUltimateInterface"}},minCount=0,raw_name={"tile.ultimate_interface"},buyPrice="13.5"},
        {text="Молекулярный сборщик",maxCount="32", needed=32,fingerprint={{dmg=0.0,id="appliedenergistics2:tile.BlockMolecularAssembler"}},minCount=0,raw_name={"tile.appliedenergistics2.blockmolecularassembler"},buyPrice="1"},
        {text="Улучшенный молек. сборщик",maxCount="32", needed=32,fingerprint={{dmg=0.0,id="dwcity:blockAdvancedMAC"}},minCount=0,raw_name={"tile.advanced_mac"},buyPrice="2.0"},
        {text="Гибридный молек. сборщик",maxCount="32", needed=32,fingerprint={{dmg=0.0,id="dwcity:blockHybridMAC"}},minCount=0,raw_name={"tile.hybrid_mac"},buyPrice="5"},
        {text="Зарядник",maxCount="16", needed=16,fingerprint={{dmg=0.0,id="appliedenergistics2:tile.BlockCharger"}},minCount=0,raw_name={"tile.appliedenergistics2.blockcharger"},buyPrice="1"},
        {text="Туннель точка-точка",maxCount="8", needed=8,fingerprint={{dmg=460.0,id="appliedenergistics2:item.ItemMultiPart"}},minCount=0,raw_name={"item.appliedenergistics2.itempart.p2ptunnel"},buyPrice="2"},
        {text="Карта ускорения",maxCount="128", needed=128,fingerprint={{dmg=30.0,id="appliedenergistics2:item.ItemMultiMaterial"}},minCount=0,raw_name={"item.appliedenergistics2.itemmaterial.cardspeed"},buyPrice="1"},
        {text="Карта создания",maxCount="32", needed=32,fingerprint={{dmg=53.0,id="appliedenergistics2:item.ItemMultiMaterial"}},minCount=0,raw_name={"item.appliedenergistics2.itemmaterial.cardcrafting"},buyPrice="0.45"},
        {text="Карта красного камня",maxCount="32", needed=32, fingerprint={{dmg=26.0,id="appliedenergistics2:item.ItemMultiMaterial"}},minCount=0,raw_name={"item.appliedenergistics2.itemmaterial.cardredstone"},buyPrice="0.45"},
        {text="МЭ терминал безопасности",maxCount="4", needed=4, fingerprint={{dmg=0.0,id="appliedenergistics2:tile.BlockSecurity"}},minCount=0,raw_name={"tile.appliedenergistics2.blocksecurity"},buyPrice="25"},
        {text="Пустой шаблон",maxCount="256", needed=256, fingerprint={{dmg=52.0,id="appliedenergistics2:item.ItemMultiMaterial"}},minCount=0,raw_name={"item.appliedenergistics2.itemmaterial.blankpattern"},buyPrice="0.7"},
        {text="4К компонент хранения",maxCount="16", needed=16,fingerprint={{dmg=36.0,id="appliedenergistics2:item.ItemMultiMaterial"}},minCount=0,raw_name={"item.appliedenergistics2.itemmaterial.cell4kpart"},buyPrice="7"},
        {text="16К компонент хранения",maxCount="8", needed=8,fingerprint={{dmg=37.0,id="appliedenergistics2:item.ItemMultiMaterial"}},minCount=0,raw_name={"item.appliedenergistics2.itemmaterial.cell16kpart"},buyPrice="15"},
        {text="64К компонент хранения",maxCount="8", needed=8,fingerprint={{dmg=38.0,id="appliedenergistics2:item.ItemMultiMaterial"}},minCount=0,raw_name={"item.appliedenergistics2.itemmaterial.cell64kpart"},buyPrice="30"},
        {text="МЭ контроллер",maxCount="128", needed=128,fingerprint={{dmg=0.0,id="appliedenergistics2:tile.BlockController"}},minCount=0,raw_name={"tile.appliedenergistics2.blockcontroller"},buyPrice="1"},
        {text="МЭ интерфейс",maxCount="64", needed=64,fingerprint={{dmg=0.0,id="appliedenergistics2:tile.BlockInterface"}},minCount=0,raw_name={"tile.appliedenergistics2.blockinterface"},buyPrice="1"},
        {text="МЭ накопитель",maxCount="8", needed=8,fingerprint={{dmg=0.0,id="appliedenergistics2:tile.BlockDrive"}},minCount=0,raw_name={"tile.appliedenergistics2.blockdrive"},buyPrice="1"},
        {text="Ускоритель роста кристаллов", needed=8,maxCount="8",fingerprint={{dmg=0.0,id="appliedenergistics2:tile.BlockQuartzGrowthAccelerator"}},minCount=0,raw_name={"tile.appliedenergistics2.blockquartzgrowthaccelerator"},buyPrice="2"},
        {text="МЭ шина экспорта",maxCount="32", needed=32,fingerprint={{dmg=260.0,id="appliedenergistics2:item.ItemMultiPart"}},minCount=0,raw_name={"item.appliedenergistics2.itempart.exportbus"},buyPrice="0.5"},
        {text="МЭ шина импорта",maxCount="32", needed=32,fingerprint={{dmg=240.0,id="appliedenergistics2:item.ItemMultiPart"}},minCount=0,raw_name={"item.appliedenergistics2.itempart.importbus"},buyPrice="0.5"},
        {text="Блок создания",maxCount="8", needed=8,fingerprint={{dmg=0.0,id="appliedenergistics2:tile.BlockCraftingUnit"}},minCount=0,raw_name={"tile.appliedenergistics2.blockcraftingunit"},buyPrice="1"},
        {text="МЭ корпус ячейки",maxCount="8", needed=8,fingerprint={{dmg=39.0,id="appliedenergistics2:item.ItemMultiMaterial"}},minCount=0,raw_name={"item.appliedenergistics2.itemmaterial.emptystoragecell"},buyPrice="0.5"},
        {text="МЭ конденсатор материи",maxCount="8", needed=8,fingerprint={{dmg=0.0,id="appliedenergistics2:tile.BlockCondenser"}},minCount=0,raw_name={"tile.appliedenergistics2.blockcondenser"},buyPrice="0.6"},
        {text="МЭ терминал создания",maxCount="8", needed=8,fingerprint={{dmg=360.0,id="appliedenergistics2:item.ItemMultiPart"}},minCount=0,raw_name={"item.appliedenergistics2.itempart.craftingterminal"},buyPrice="1"},
        {text="Высекатель",maxCount="16",needed=16,fingerprint={{dmg=0.0,id="appliedenergistics2:tile.BlockInscriber"}},minCount=0,raw_name={"tile.appliedenergistics2.blockinscriber"},buyPrice="1"},
        {text="Продвинутый высекатель",maxCount="4",needed=4,fingerprint={{dmg=0.0,id="ae2stuff:Inscriber"}},minCount=0,raw_name={"tile.ae2stuff.inscriber"},buyPrice="80"},

        --ic2
        {text = "Резина", buyPrice = 0.01, minCount = 0, maxCount = 1024, fingerprint = {{dmg=0.0,id="IC2:itemRubber"}}, raw_name = {"ic2.itemrubber"}},
        {text = "Углепластик", buyPrice = 0.5, minCount = 0, needed = 128, maxCount = 128, fingerprint = {{dmg=0.0,id="IC2:itemPartCarbonPlate"}}, raw_name = {"ic2.itempartcarbonplate"}},
        {text = "Слиток закаленного железа", buyPrice = 0.3, minCount = 0, maxCount = 128, fingerprint = {{dmg=3.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingotadviron"}},
        {text = "Оловянный слиток", buyPrice = 0.1, minCount = 0, maxCount = 1024, fingerprint = {{dmg=1.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingottin"}},
        {text = "Серебрянный слиток", buyPrice = 0.1, minCount = 0, maxCount = 1024, fingerprint = {{dmg=6.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingotsilver"}},
        {text = "Свинцовый слиток", buyPrice = 0.1, minCount = 0, maxCount = 1024, fingerprint = {{dmg=5.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingotlead"}},
        {text = "Уран 238", buyPrice = 0.2, minCount = 0, maxCount = 1024, fingerprint = {{dmg=0.0,id="IC2:itemUran238"}}, raw_name = {"ic2.itemuran238"}},
        {text = "Кусочек урана 235", buyPrice = 0.5, minCount = 0, maxCount = 512, fingerprint = {{dmg=0.0,id="IC2:itemUran235small"}}, raw_name = {"ic2.itemuran235small"}},
        {text = "Энергетический кристалл", buyPrice = 2, minCount = 0, maxCount = 16, needed = 16, ignoreDamage = true, fingerprint = {{dmg=27.0,id="IC2:itemBatCrystal"}}, raw_name = {"ic2.itembatcrystal"}},
        {text = "Лазуротроновый кристалл", buyPrice = 5, minCount = 0, maxCount = 16, needed = 16, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemBatLamaCrystal"}}, raw_name = {"ic2.itembatlamacrystal"}},

        {text = "Иридий", buyPrice = 10, minCount = 0, maxCount = 10, needed = 10, fingerprint = {{id="IC2:itemOreIridium",dmg=0.0}}, raw_name = {"ic2.itemoreiridium"}},
        {text = "Укр. иридиевая пластина", buyPrice = 40, minCount = 0, needed = 8, maxCount = 8, fingerprint = {{id="IC2:itemPartIridium",dmg=0.0}}, raw_name = {"ic2.itempartiridium"}},
        {text = "Ускоритель", buyPrice = 11, minCount = 0, needed = 32, maxCount = 32, fingerprint = {{dmg=0.0,id="IC2:upgradeModule"}}, raw_name = {"ic2.overclockerupgrade"}},
        {text = "Композит", buyPrice = 0.5, minCount = 0, maxCount = 128, needed = 128, fingerprint = {{dmg=0.0,id="IC2:itemPartAlloy"}}, raw_name = {"ic2.itempartalloy"}},
        {text = "Капсула хладагента", buyPrice = 0.5, needed = 256, minCount = 0, maxCount = 256, fingerprint = {{dmg=9.0,id="IC2:itemCellEmpty"}}, raw_name = {"ic2.itemcellcoolant"}},
        {text = "Солн. панель 1-го ур.", buyPrice = 1.5, minCount = 0, maxCount = 2048, fingerprint = {{dmg=3.0,id="IC2:blockGenerator"}}, raw_name = {"ic2.blocksolargenerator"}},
        {text = "Солн. панель 2-го ур.", buyPrice = 12, needed = 16, minCount = 0, maxCount = 512, fingerprint = {{dmg=0.0,id="CompactSolars:CompactSolarBlock"}}, raw_name = {"tile.compactsolars.lv_block"}},
        {text = "Солн. панель 3-го ур.", buyPrice = 100, needed = 4, minCount = 0, maxCount = 64, fingerprint = {{dmg=1.0,id="CompactSolars:CompactSolarBlock"}}, raw_name = {"tile.compactsolars.mv_block"}},
        {text = "Солн. панель 4-го ур.", buyPrice = 800, needed = 1, minCount = 0, maxCount = 4, fingerprint = {{dmg=2.0,id="CompactSolars:CompactSolarBlock"}}, raw_name = {"tile.compactsolars.hv_block"}},
        {text = "Сверхпроводник", buyPrice = 55, minCount = 0, needed = 6, maxCount = 6, fingerprint = {{dmg=1.0,id="GraviSuite:itemSimpleItem"}}, raw_name = {"item.superconductor"}},
        {text="Релокатор", minCount=0,buyPrice="300",maxCount="3",fingerprint={{id="GraviSuite:relocator",dmg=1.0}}, raw_name={"item.relocator"}, ignoreDamage = true},
        {text="Улучшенный алм. бур", minCount=0,buyPrice="50",maxCount="4",fingerprint={{id="GraviSuite:advDDrill",dmg=0.0}}, raw_name={"item.advddrill"}, ignoreDamage = true},
        {text="Гравитационный жилет", minCount=0,buyPrice="700",maxCount="3",fingerprint={{id="GraviSuite:graviChestPlate",dmg=0.0}},raw_name={"item.gravichestplate"}, ignoreDamage = true},
        {text = "Компрессор", buyPrice = 4, minCount = 0, needed = 4, maxCount = 4, fingerprint = {{dmg=5.0,id="IC2:blockMachine"}}, raw_name = {"ic2.blockcompressor"}},
        {text = "Электропечь", buyPrice = 3, minCount = 0, needed = 4, maxCount = 4, fingerprint = {{dmg=2.0,id="IC2:blockMachine"}}, raw_name = {"ic2.blockelecfurnace"}},
        {text = "Дробитель", buyPrice = 4, minCount = 0, needed = 4, maxCount = 4, fingerprint = {{dmg=3.0,id="IC2:blockMachine"}}, raw_name = {"ic2.blockmacerator"}},
        {text = "Рудопромывочный механизм", buyPrice = 5, needed = 4, minCount = 0, maxCount = 4, fingerprint = {{dmg=5.0,id="IC2:blockMachine2"}}, raw_name = {"ic2.blockorewashingplant"}},
        {text = "Термальная центрифуга", buyPrice = 8, needed = 4, minCount = 0, maxCount = 4, fingerprint = {{dmg=3.0,id="IC2:blockMachine2"}}, raw_name = {"ic2.blockcentrifuge"}},
        {text = "Металлоформовочный механизм", buyPrice = 5, needed = 8, minCount = 0, maxCount = 8, fingerprint = {{dmg=4.0,id="IC2:blockMachine2"}}, raw_name = {"ic2.blockmetalformer"}},
        {text = "Экстрактор", buyPrice = 4, needed = 4, minCount = 0, maxCount = 4, fingerprint = {{dmg=4.0,id="IC2:blockMachine"}}, raw_name = {"ic2.blockextractor"}},
        {text = "Квантовый компрессор", buyPrice = 70, needed = 2, minCount = 0, maxCount = 2, fingerprint = {{dmg=3.0,id="dwcity:AdvancedMachine"}}, raw_name = {"dw.blockadvancedcompressor"}},
        {text = "Квантовая печь", buyPrice = 70, needed = 2, minCount = 0, maxCount = 2, fingerprint = {{dmg=0.0,id="dwcity:AdvancedMachine"}}, raw_name = {"dw.blockadvancedfurnace"}},
        {text = "Квантовый дробитель", buyPrice = 70, needed = 2, minCount = 0, maxCount = 2, fingerprint = {{dmg=1.0,id="dwcity:AdvancedMachine"}}, raw_name = {"dw.blockadvancedmacerator"}},
        {text = "Квантовый рудопромыв. мех.", buyPrice = 70, needed = 2, minCount = 0, maxCount = 2, fingerprint = {{dmg=6.0,id="dwcity:AdvancedMachine"}}, raw_name = {"dw.blockadvancedorewashing"}},
        {text = "Квантовая термал. центриф.", buyPrice = 70, needed = 2, minCount = 0, maxCount = 2, fingerprint = {{dmg=4.0,id="dwcity:AdvancedMachine"}}, raw_name = {"dw.blockadvancedcentrifuge"}},
        {text = "Квантовый металлоформ. мех.", buyPrice = 70, needed = 2, minCount = 0, maxCount = 2, fingerprint = {{dmg=5.0,id="dwcity:AdvancedMachine"}}, raw_name = {"dw.blockadvancedmetalformer"}},
        {text = "Квантовый экстрактор", buyPrice = 70, needed = 2, minCount = 0, maxCount = 2, fingerprint = {{dmg=2.0,id="dwcity:AdvancedMachine"}}, raw_name = {"dw.blockadvancedextractor"}},

        {text = "Нано-сабля", buyPrice = 5, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=1.0,id="IC2:itemNanoSaber"}}, raw_name = {"ic2.itemnanosaber"}},
        {text = "Нано-шлем", buyPrice = 7, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=0.0,id="IC2:itemArmorNanoHelmet"}}, raw_name = {"ic2.itemarmornanohelmet"}},
        {text = "Нано-поножи", buyPrice = 4, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorNanoLegs"}}, raw_name = {"ic2.itemarmornanolegs"}},
        {text = "Нано-ботинки", buyPrice = 3, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorNanoBoots"}}, raw_name = {"ic2.itemarmornanoboots"}},
        {text = "Квантовый шлем", buyPrice = 75, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumHelmet"}}, raw_name = {"ic2.itemarmorquantumhelmet"}},
        {text = "Квантовая кираса", buyPrice = 100, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumChestplate"}}, raw_name = {"ic2.itemarmorquantumchestplate"}},
        {text = "Квантовые поножи", buyPrice = 75, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumLegs"}}, raw_name = {"ic2.itemarmorquantumlegs"}},
        {text = "Квантовые ботинки", buyPrice = 75, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumBoots"}}, raw_name = {"ic2.itemarmorquantumboots"}},
        {text = "Улучшенный наножилет", buyPrice = 30, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="GraviSuite:advNanoChestPlate"}}, raw_name = {"item.advnanochestplate"}},

        --thaumcraft
        {text = "Семя пустоты", buyPrice = 0.3, minCount = 0, maxCount = 16, needed=16, fingerprint = {{dmg=17.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.17"}},
        {text = "Нитор", buyPrice = 0.1, minCount = 0, maxCount = 32, needed=32, fingerprint = {{dmg=1.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.1"}},
        {text = "Грозовой кристалл", buyPrice = 0.05, minCount = 0, maxCount = 128, fingerprint = {{dmg=0.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.0"}},
        {text = "Огненный кристалл", buyPrice = 0.05, minCount = 0, maxCount = 128, fingerprint = {{dmg=1.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.1"}},
        {text = "Ледяной кристалл", buyPrice = 0.05, minCount = 0, maxCount = 128, fingerprint = {{dmg=2.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.2"}},
        {text = "Земляной кристалл", buyPrice = 0.05, minCount = 0, maxCount = 128, fingerprint = {{dmg=3.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.3"}},
        {text = "Кристалл порядка", buyPrice = 0.05, minCount = 0, maxCount = 128, fingerprint = {{dmg=4.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.4"}},
        {text = "Энтропийный кристалл", buyPrice = 0.05, minCount = 0, maxCount = 128, fingerprint = {{dmg=5.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.5"}},
        {text = "Сбалансированный кристалл", buyPrice = 0.3, minCount = 0, maxCount = 128, fingerprint = {{dmg=6.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.6"}},
        {text = "Ихор", buyPrice = 12, minCount = 0, maxCount = 32, needed=16, fingerprint = {{dmg=0.0,id="ThaumicTinkerer:kamiResource"}}, raw_name = {"item.kamiresource"}},
        {text = "Зараженное щупальце", buyPrice = 0.5, minCount = 0, maxCount = 1024, fingerprint = {{dmg=12.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.12"}},
        {text = "Зараженная слизь", buyPrice = 0.5, minCount = 0, maxCount = 512, fingerprint = {{dmg=11.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.11"}},
        {text = "Мозг зомби", buyPrice = 0.2, minCount = 0, maxCount = 512, fingerprint = {{dmg=0.0,id="Thaumcraft:ItemZombieBrain"}}, raw_name = {"item.itemzombiebrain"}},
        {text = "Кристалл края", buyPrice = 2, minCount = 0, maxCount = 32, needed=16, fingerprint = {{dmg=7.0,id="ThaumicTinkerer:kamiResource"}}, raw_name = {"item.kamiresource"}},
        {text = "Кристалл нижнего мира", buyPrice = 2, minCount = 0, maxCount = 32, needed=16, fingerprint = {{dmg=6.0,id="ThaumicTinkerer:kamiResource"}}, raw_name = {"item.kamiresource"}},
        {text = "Эфирная эссенция", buyPrice = 0.4, minCount = 0, maxCount = 512, fingerprint = {{dmg=0.0,id="Thaumcraft:ItemWispEssence"}}, raw_name = {"item.itemwispessence"}},
        {text = "Фрагмент знаний", buyPrice = 0.1, minCount = 0, maxCount = 1024, needed=1024, fingerprint = {{dmg=9.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.9"}},
        {text = "Ртуть", buyPrice = 0.1, minCount = 0, maxCount = 1024, fingerprint = {{dmg=3.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.3"}},
        {text = "Алюментум", buyPrice = 0.1, minCount = 0, maxCount = 32, needed=16, fingerprint = {{dmg=0.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.0"}},
        {text="Поставщик наполнения", minCount = 0, raw_name={"thaumicenergistics.block.infusion.provider"}, buyPrice= 5, needed = 4, maxCount= 2,fingerprint={{id="thaumicenergistics:thaumicenergistics.block.infusion.provider",dmg=0.0}}},
        {text="Ткань поглощения заклинаний", minCount=0,raw_name={"item.spellcloth"},fingerprint={{id="ThaumicTinkerer:spellCloth",dmg=0.0}},maxCount= 4,buyPrice= 1, needed = 4},
        {text="Обсидиановый тотем", minCount=0,raw_name={"tile.blockcosmeticsolid.0"},fingerprint={{id="Thaumcraft:blockCosmeticSolid",dmg=0.0}},maxCount=24,needed=24, buyPrice=2},
        {text="Таум-слиток", minCount=0,raw_name={"item.itemresource.2"},fingerprint={{id="Thaumcraft:ItemResource",dmg=2.0}},maxCount=128, buyPrice=0.2},
        {text="Узел-стабилизатор", minCount=0,raw_name={"tile.blockstonedevice.9"},fingerprint={{id="Thaumcraft:blockStoneDevice",dmg=9.0}},maxCount=4,needed = 4, buyPrice = 1},
        {text="Узел-преобразователь", minCount=0,raw_name={"tile.blockstonedevice.11"},fingerprint={{id="Thaumcraft:blockStoneDevice",dmg=11.0}},maxCount= 4,needed = 4, buyPrice = 3},
        {text="Зачарованная ткань", minCount=0,raw_name={"item.itemresource.7"},fingerprint={{id="Thaumcraft:ItemResource",dmg=7.0}},maxCount= 256,buyPrice = 0.1},
        {text="Улучшенная алхим. конструкция", minCount=0,raw_name={"tile.blockmetaldevice.3"},fingerprint={{id="Thaumcraft:blockMetalDevice",dmg=3.0}},maxCount=16,needed=16, buyPrice = 3},
        {text="Алхимическая конструкция", minCount=0,raw_name={"tile.blockmetaldevice.9"},fingerprint={{id="Thaumcraft:blockMetalDevice",dmg=9.0}},maxCount=32,needed=16, buyPrice=0.3},
        {text="Осмотрический стол зачар.", minCount=0,raw_name={"tile.enchanter"},fingerprint={{id="ThaumicTinkerer:enchanter",dmg=0.0}},maxCount=2 ,buyPrice= 130},
        {text="Ихорный стержень",minCount=0,raw_name={"item.kamiresource"},fingerprint={{id="ThaumicTinkerer:kamiResource",dmg=5.0}},maxCount=2,needed=2,buyPrice=45},
        {text="Поставщик эссенции",minCount=0,raw_name={"thaumicenergistics.block.essentia.provider"},fingerprint={{id="thaumicenergistics:thaumicenergistics.block.essentia.provider",dmg=0.0}},maxCount=2,needed=2, buyPrice=5},
        {minCount=0, raw_name={"item.ichorswordgem"}, fingerprint={{id="ThaumicTinkerer:ichorSwordGem",dmg=0.0}}, maxCount= 2, text="Пробужд. ихор меч", buyPrice=300, needed=2, ignoreDamage = true},
        {minCount=0,raw_name={"item.ichorshovelgem"},fingerprint={{id="ThaumicTinkerer:ichorShovelGem",dmg=0.0}},maxCount=2,text="Пробужд. ихор лопата",buyPrice=300,needed=2,  ignoreDamage = true},
        {minCount=0,raw_name={"item.ichoraxegem"},fingerprint={{id="ThaumicTinkerer:ichorAxeGem",dmg=0.0}},maxCount=2,text="Пробужд. ихор топор",buyPrice= 300,needed=2,  ignoreDamage = true},
        {minCount=0,raw_name={"item.ichorpickgem"},fingerprint={{id="ThaumicTinkerer:ichorPickGem",dmg=0.0}},maxCount=2,text="Пробужд. ихор кирка",buyPrice=300, needed=2, ignoreDamage = true},
        {minCount=0,raw_name={"item.ichorclothboots"},fingerprint={{id="ThaumicTinkerer:ichorclothBoots",dmg=0.0}},maxCount=2,text="Ихоровые сапоги",buyPrice=60, needed=2,  ignoreDamage = true},
        {minCount=0,raw_name={"item.ichorclothlegs"},fingerprint={{id="ThaumicTinkerer:ichorclothLegs",dmg=0.0}},maxCount=2,text="Ихоровые шаровары",buyPrice=105,needed=2, ignoreDamage = true},
        {minCount=0,raw_name={"item.ichorclothchest"},fingerprint={{id="ThaumicTinkerer:ichorclothChest",dmg=0.0}},maxCount=2,text="Ихоровая роба",buyPrice=120, needed=2, ignoreDamage = true},
        {minCount=0,raw_name={"item.ichorclothhelm"},fingerprint={{id="ThaumicTinkerer:ichorclothHelm",dmg=0.0}},maxCount=2,text="Ихоровый капюшон",buyPrice=75, needed=2, ignoreDamage = true},

        --forestry
        {text = "Скопление пыльцы", buyPrice = 0.02, minCount = 0, maxCount = 512, fingerprint = {{id="Forestry:pollen",dmg=0.0}}, raw_name = {"item.for.pollen.normal"}},
        {text = "Маточное молочко", buyPrice = 0.02, minCount = 0, maxCount = 512, fingerprint = {{id="Forestry:royalJelly",dmg=0.0}}, raw_name = {"item.for.royaljelly"}},
        {text = "Пропитанный корпус", buyPrice = 0.6, minCount = 0, maxCount = 512, fingerprint = {{id="Forestry:impregnatedCasing",dmg=0.0}}, raw_name = {"item.for.impregnatedcasing"}},
        {text = "Пропитанная обшивка", buyPrice = 0.3, minCount = 0, maxCount = 1024, fingerprint = {{id="Forestry:craftingMaterial",dmg=6.0}}, raw_name = {"item.for.craftingmaterial.scentedpaneling"}},
        {text = "Капля меда", buyPrice = 0.01, minCount = 0, maxCount = 2048, fingerprint = {{id="Forestry:honeyDrop",dmg=0.0}}, raw_name = {"item.for.honeydrop.honey"}},
        {text = "Фермент", buyPrice = 0.5, minCount = 0, maxCount = 64, fingerprint = {{id="Genetics:misc",dmg=3.0}}, raw_name = {"item.misc"}},
        {text = "Необычная пыльца", buyPrice = 0.1, minCount = 0, maxCount = 512, fingerprint = {{id="MagicBees:pollen",dmg=0.0}}, raw_name = {"item.pollen"}},
        {text = "Зачарованная капля", buyPrice = 0.1, minCount = 0, maxCount = 512, fingerprint = {{id="MagicBees:drop",dmg=0.0}}, raw_name = {"item.drop"}},
        {text = "Магический воск", buyPrice = 0.02, minCount = 0, maxCount = 512, fingerprint = {{id="MagicBees:wax",dmg=0.0}}, raw_name = {"item.wax"}},
        {text = "Пчелиный воск", buyPrice = 0.01, minCount = 0, maxCount = 512, fingerprint = {{id="Forestry:beeswax",dmg=0.0}}, raw_name = {"item.for.beeswax"}},
        {text = "Бронзовый слиток", buyPrice = 0.3, minCount = 0, maxCount = 512, needed = 128,  fingerprint = {{id="Forestry:ingotBronze",dmg=0.0}}, raw_name = {"item.for.ingotbronze"}},

        --thermal
        {text = "Синаловый слиток", buyPrice = 1, minCount = 0, maxCount = 32, needed=32, fingerprint = {{dmg=74.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotsignalum"}},
        {text = "Слиток эндериума", buyPrice = 2, minCount = 0, maxCount = 32, needed=32, fingerprint = {{dmg=76.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotenderium"}},
        {text = "Ламиумовый слиток", buyPrice = 1, minCount = 0, maxCount = 32, needed=32, fingerprint = {{dmg=75.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotlumium"}},
        {text = "Платиновый слиток", buyPrice = 1, minCount = 0, maxCount = 64, needed=32, fingerprint = {{dmg=69.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotplatinum"}},
        {text = "Никелевый слиток", buyPrice = 0.1, minCount = 0, maxCount = 64, fingerprint = {{dmg=68.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotnickel"}},
        {text = "Электрумовый слиток", buyPrice = 0.3, minCount = 0, maxCount = 128, needed=32, fingerprint = {{dmg=71.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotelectrum"}},
        {text = "Обогащенный шлак", buyPrice = 0.2, minCount = 0, maxCount = 512, fingerprint = {{dmg=515.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.slagrich"}},

        --dwcity
        {text = "Флаксовый слиток", buyPrice = 1.1, minCount = 0, maxCount = 32, needed=32, ignoreDamage = true, fingerprint = {{dmg=32.0,id="dwcity:Flux_ingot"}}, raw_name = {"item.redstonearsenal.material.ingotelectrumflux"}},
        {text = "Дракониевый кристалл", buyPrice = 7, minCount = 0, maxCount = 32, needed=32, fingerprint = {{dmg=0.0,id="dwcity:Dragon_shard"}}, raw_name = {"item.dragon_shard"}},
        {text = "Ториевый слиток", buyPrice = 0.3, minCount = 0, maxCount = 256, fingerprint = {{dmg=0.0,id="dwcity:Thorium_ingot"}}, raw_name = {"item.thorium_ingot"}},
        {text = "Трижды сжатый камень", buyPrice = 10, minCount = 0, maxCount = 16, fingerprint = {{dmg=0.0,id="dwcity:Powder11"}}, raw_name = {"item.powder11"}},
        {text = "Темная материя", buyPrice = 2.5, minCount = 0, maxCount = 64, fingerprint = {{dmg=0.0,id="dwcity:Dark_materia"}}, raw_name = {"item.dark_materia"}},
        {text = "Ледяная материя", buyPrice = 2.5, minCount = 0, maxCount = 64, fingerprint = {{dmg=0.0,id="dwcity:Sky_materia"}}, raw_name = {"item.sky_materia"}},
        {text = "Вис материя", buyPrice = 2.5, minCount = 0, maxCount = 64, fingerprint = {{dmg=0.0,id="dwcity:Vis_materia"}}, raw_name = {"item.vis_materia"}},
        {text = "Живая материя", buyPrice = 2.5, minCount = 0, maxCount = 64, fingerprint = {{dmg=0.0,id="dwcity:Live_materia"}}, raw_name = {"item.live_materia"}},
        {text = "Солнечная материя", buyPrice = 2.5, minCount = 0, maxCount = 64, fingerprint = {{dmg=0.0,id="dwcity:Fire_materia"}}, raw_name = {"item.fire_materia"}},
        {maxCount=4,text="Аместист",buyPrice=12,needed=4, raw_name={"item.amethyst"},fingerprint={{id="dwcity:Amethyst",dmg=0.0}},minCount=0},
        {maxCount=4,text="Топаз",buyPrice=0.3,needed=4, raw_name={"item.topaz"},fingerprint={{id="dwcity:Topaz",dmg=0.0}},minCount=0},
        {maxCount=4,text="Танзанит",buyPrice=5,needed=4, raw_name={"item.tanzanit"},fingerprint={{id="dwcity:Tanzanit",dmg=0.0}},minCount=0},
        {maxCount=4,text="Гранат",buyPrice=2.5,needed=4, raw_name={"item.granat"},fingerprint={{id="dwcity:Granat",dmg=0.0}},minCount=0},
        {maxCount=4,text="Аквамарин",buyPrice=15,needed=4, raw_name={"item.akvamarin"},fingerprint={{id="dwcity:Akvamarin",dmg=0.0}},minCount=0},
        {maxCount=8,text="Базовый чертеж",buyPrice=1,needed=6, raw_name={"item.basic_plan"},fingerprint={{id="dwcity:Basic_plan",dmg=0.0}},minCount=0},
        {maxCount=8,text="Улучшенный чертеж",buyPrice=2,needed=6, raw_name={"item.rare_plan"},fingerprint={{id="dwcity:Rare_plan",dmg=0.0}},minCount=0},
        {maxCount=8,text="Уникальный чертеж",buyPrice=4, raw_name={"item.epic_plan"},fingerprint={{id="dwcity:Epic_plan",dmg=0.0}},minCount=0},
        {text = "Камень тьмы", buyPrice = 1, minCount = 0, maxCount = 8, needed=8, fingerprint = {{dmg=0.0,id="dwcity:Dark_stone"}}, raw_name = {"item.dark_stone"}},
        {text = "Заклинание тьмы", buyPrice = 50, minCount = 0, maxCount = 2, needed=2, fingerprint = {{dmg=0.0,id="customnpcs:npcDarkSpell"}}, raw_name = {"item.npcdarkspell"}},

        --draconic
        {text = "Дракониевый слиток", buyPrice = 2, minCount = 0, maxCount = 256, fingerprint = {{dmg=0.0,id="DraconicEvolution:draconiumIngot"}}, raw_name = {"item.draconicevolution:draconiumingot"}},
        {text = "Пробужденный дк слиток", buyPrice = 20, minCount = 0, maxCount = 16,needed=16,  fingerprint = {{dmg=0.0,id="DraconicEvolution:draconicIngot"}}, raw_name = {"item.draconicevolution:draconicingot"}},
        {text = "Дракониевая пыль", buyPrice = 0.4, minCount = 0, maxCount = 512, fingerprint = {{dmg=0.0,id="DraconicEvolution:draconiumDust"}}, raw_name = {"item.draconicevolution:draconiumdust"}},

        --botania

    },

    ore = {
        {text="Железная руда",ratio=2.33,raw_name={"tile.oreiron"},fingerprint={{dmg=0.0,id="minecraft:iron_ingot"}}},
        {text="Золотая руда",ratio=2.33,raw_name={"tile.oregold"},fingerprint={{dmg=0.0,id="minecraft:gold_ingot"}}},
        {text="Медная руда",ratio=2.33,raw_name={"tile.thermalfoundation.ore.copper.name","ic2.blockorecopper"},fingerprint={{dmg=64.0,id="ThermalFoundation:material"},{dmg=0.0,id="IC2:itemIngot"},{dmg=0.0,id="ImmersiveEngineering:metal"},{dmg=5.0,id="Mekanism:Ingot"}}},
        {text="Оловянная руда",ratio=2.33,raw_name={"tile.thermalfoundation.ore.tin.name","ic2.blockoretin"},fingerprint={{dmg=6.0,id="Mekanism:Ingot"},{dmg=65.0,id="ThermalFoundation:material"},{dmg=1.0,id="IC2:itemIngot"}}},
        {text="Серебряная руда",ratio=2.33,raw_name={"tile.thermalfoundation.ore.silver.name"},fingerprint={{dmg=66.0,id="ThermalFoundation:material"},{dmg=6.0,id="IC2:itemIngot"}}},
        {text="Осмиевая руда",ratio=2.33,raw_name={"tile.oreblock.osmiumore"},fingerprint={{dmg=1.0,id="Mekanism:Ingot"}}},
        {text="Свинцовая руда",ratio=2.33,raw_name={"tile.thermalfoundation.ore.lead.name","ic2.blockorelead"},fingerprint={{dmg=67.0,id="ThermalFoundation:material"},{dmg=5.0,id="IC2:itemIngot"}}}
    },

    food = {{dmg=0.0, id="minecraft:cooked_beef"}}
}
