{
    shop = {
        {text = "Деньги", sellPrice = 1, buyPrice = 1, minCount = 1, maxCount = 1024, fingerprint = {{dmg=0.0,id="customnpcs:npcMoney"}}, raw_name = {"item.npcmoney"}},

        {text = "Алмаз", buyPrice = 0.4, minCount = 1, maxCount = 2048, fingerprint = {{dmg=0.0,id="minecraft:diamond"}}, raw_name = {"item.diamond"}},
        {text = "Уголь", buyPrice = 0.05, minCount = 1, maxCount = 2048, fingerprint = {{dmg=0.0,id="minecraft:coal"}}, raw_name = {"item.coal"}},
        {text = "Кристалл истинного кварца", buyPrice = 0.2, minCount = 1, maxCount = 2048, fingerprint = {{dmg=0.0,id="appliedenergistics2:item.ItemMultiMaterial"}}, raw_name = {"item.appliedenergistics2.itemmaterial.certusquartzcrystal"}},
        {text = "Зар. кристалл ист. кварца", buyPrice = 0.5, minCount = 1, maxCount = 2048, fingerprint = {{dmg=1.0,id="appliedenergistics2:item.ItemMultiMaterial"}}, raw_name = {"item.appliedenergistics2.itemmaterial.certusquartzcrystalcharged"}},
        {text = "Энергетический кристалл", buyPrice = 2, minCount = 1, maxCount = 16, needed = 16, ignoreDamage = true, fingerprint = {{dmg=27.0,id="IC2:itemBatCrystal"}}, raw_name = {"ic2.itembatcrystal"}},
        {text = "Лазуротроновый кристалл", buyPrice = 5, minCount = 1, maxCount = 16, needed = 16, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemBatLamaCrystal"}}, raw_name = {"ic2.itembatlamacrystal"}},
        {text = "Семя пустоты", buyPrice = 0.1, minCount = 1, maxCount = 16, needed = 16, fingerprint = {{dmg=17.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.17"}},
        {text = "Шерсть", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:wool",dmg=0.0}}, raw_name = {"tile.cloth.white"}},
        {text = "Красная пыль", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:redstone",dmg=0.0}}, raw_name = {"item.redstone"}},
        {text = "Светопыль", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:glowstone_dust",dmg=0.0}}, raw_name = {"item.yellowdust"}},
        {text = "Кость", buyPrice = 0.2, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:bone",dmg=0.0}}, raw_name = {"item.bone"}},
        {text = "Гнилая плоть", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:rotten_flesh",dmg=0.0}}, raw_name = {"item.rottenflesh"}},
        {text = "Жемчуг эндера", buyPrice = 0.4, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:ender_pearl",dmg=0.0}}, raw_name = {"item.enderpearl"}},
        {text = "Изумруд", buyPrice = 1, minCount = 1, maxCount = 512, fingerprint = {{id="minecraft:emerald",dmg=0.0}}, raw_name = {"item.emerald"}},
        {text = "Череп скелета", buyPrice = 0.2, minCount = 1, maxCount = 256, fingerprint = {{id="minecraft:skull",dmg=0.0}}, raw_name = {"item.skull.skeleton"}},
        {text = "Голова зомби", buyPrice = 0.2, minCount = 1, maxCount = 256, fingerprint = {{id="minecraft:skull",dmg=2.0}}, raw_name = {"item.skull.zombie"}},
        {text = "Выч. пресс для высекателя", buyPrice = 0.25, minCount = 1, maxCount = 512, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=13.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.calcprocessorpress"}},
        {text = "Инж. пресс для высекателя", buyPrice = 0.45, minCount = 1, maxCount = 512, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=14.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.engprocessorpress"}},
        {text = "Лог. пресс для высекателя", buyPrice = 0.15, minCount = 1, maxCount = 512, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=15.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.logicprocessorpress"}},
        {text = "Сингулярность", buyPrice = 2, minCount = 1, maxCount = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=47.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.singularity"}},
        {text = "Череп Скелета-Иссушителя", buyPrice = 30, minCount = 1, needed = 128, maxCount = 128, fingerprint = {{dmg=1.0,id="minecraft:skull"}}, raw_name = {"item.skull.wither"}},
        {text = "Укр. иридиевая пластина", buyPrice = 40, minCount = 1, needed = 8, maxCount = 8, fingerprint = {{id="IC2:itemPartIridium",dmg=0.0}}, raw_name = {"ic2.itempartiridium"}},
        {text = "Кварц", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{dmg=0.0,id="minecraft:quartz"}}, raw_name = {"item.netherquartz"}},
        {text = "Синаловый слиток", buyPrice = 1, minCount = 1, maxCount = 32, needed = 32, fingerprint = {{dmg=74.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotsignalum"}},
        {text = "Флаксовый слиток", buyPrice = 1.1, minCount = 1, maxCount = 32, needed = 32, ignoreDamage = true, fingerprint = {{dmg=32.0,id="dwcity:Flux_ingot"}}, raw_name = {"item.redstonearsenal.material.ingotelectrumflux"}},
        {text = "Ускоритель", buyPrice = 11, minCount = 1, needed = 32, maxCount = 32, fingerprint = {{dmg=0.0,id="IC2:upgradeModule"}}, raw_name = {"ic2.overclockerupgrade"}},
        {text = "Перо", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{dmg=0.0,id="minecraft:feather"}}, raw_name = {"item.feather"}},
        {text = "Слиток эндериума", buyPrice = 2, minCount = 1, maxCount = 32, needed = 32, fingerprint = {{dmg=76.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotenderium"}},
        {text = "Стержень ифрита", buyPrice = 0.5, minCount = 1, maxCount = 512, fingerprint = {{id="minecraft:blaze_rod",dmg=0.0}}, raw_name = {"item.blazerod"}},
        {text = "Сгусток слизи", buyPrice = 0.5, minCount = 1, maxCount = 512, fingerprint = {{id="minecraft:slime_ball",dmg=0.0}}, raw_name = {"item.slimeball"}},
        {text = "Фрагмент знаний", buyPrice = 0.1, minCount = 1, maxCount = 1024, needed = 1024, fingerprint = {{id="Thaumcraft:ItemResource",dmg=9.0}}, raw_name = {"item.itemresource.9"}},
        {text = "Композит", buyPrice = 0.5, minCount = 1, maxCount = 128, needed = 128, fingerprint = {{dmg=0.0,id="IC2:itemPartAlloy"}}, raw_name = {"ic2.itempartalloy"}},
        {text = "Нано-сабля", buyPrice = 1500, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=1.0,id="IC2:itemNanoSaber"}}, raw_name = {"ic2.itemnanosaber"}},
        {text = "Нано-шлем", buyPrice = 2000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=0.0,id="IC2:itemArmorNanoHelmet"}}, raw_name = {"ic2.itemarmornanohelmet"}},
        {text = "Нано-поножи", buyPrice = 1500, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorNanoLegs"}}, raw_name = {"ic2.itemarmornanolegs"}},
        {text = "Нано-ботинки", buyPrice = 1500, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorNanoBoots"}}, raw_name = {"ic2.itemarmornanoboots"}},
        {text = "Квантовый шлем", buyPrice = 17000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumHelmet"}}, raw_name = {"ic2.itemarmorquantumhelmet"}},
        {text = "Квантовая кираса", buyPrice = 15000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumChestplate"}}, raw_name = {"ic2.itemarmorquantumchestplate"}},
        {text = "Квантовые поножи", buyPrice = 15000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumLegs"}}, raw_name = {"ic2.itemarmorquantumlegs"}},
        {text = "Квантовые ботинки", buyPrice = 15000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumBoots"}}, raw_name = {"ic2.itemarmorquantumboots"}},
        {text = "Улучшенный наножилет", buyPrice = 16000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="GraviSuite:advNanoChestPlate"}}, raw_name = {"item.advnanochestplate"}},
        {text = "Капсула хладагента", buyPrice = 0.5, minCount = 1, maxCount = 256, needed = 256, fingerprint = {{dmg=9.0,id="IC2:itemCellEmpty"}}, raw_name = {"ic2.itemcellcoolant"}},
        {text = "Скопление пыльцы", buyPrice = 0.02, minCount = 1, maxCount = 512, fingerprint = {{id="Forestry:pollen",dmg=0.0}}, raw_name = {"item.for.pollen.normal"}},
        {text = "Маточное молочко", buyPrice = 0.02, minCount = 1, maxCount = 512, fingerprint = {{id="Forestry:royalJelly",dmg=0.0}}, raw_name = {"item.for.royaljelly"}},
        {text = "Иридий", buyPrice = 10, minCount = 1, maxCount = 10, needed = 10, fingerprint = {{id="IC2:itemOreIridium",dmg=0.0}}, raw_name = {"ic2.itemoreiridium"}},
        {text = "Слеза Гаста", buyPrice = 0.4, minCount = 1, maxCount = 512, fingerprint = {{id="minecraft:ghast_tear",dmg=0.0}}, raw_name = {"item.ghasttear"}}
    },

    ore = {
        {text="Железная руда",ratio=3,raw_name={"tile.oreiron"},fingerprint={{dmg=0.0,id="minecraft:iron_ingot"}}},
        {text="Золотая руда",ratio=3,raw_name={"tile.oregold"},fingerprint={{dmg=0.0,id="minecraft:gold_ingot"}}},
        {text="Медная руда",ratio=3,raw_name={"tile.thermalfoundation.ore.copper.name","ic2.blockorecopper"},fingerprint={{dmg=64.0,id="ThermalFoundation:material"},{dmg=0.0,id="IC2:itemIngot"},{dmg=0.0,id="ImmersiveEngineering:metal"},{dmg=5.0,id="Mekanism:Ingot"}}},
        {text="Оловянная руда",ratio=3,raw_name={"tile.thermalfoundation.ore.tin.name","ic2.blockoretin"},fingerprint={{dmg=6.0,id="Mekanism:Ingot"},{dmg=65.0,id="ThermalFoundation:material"},{dmg=1.0,id="IC2:itemIngot"}}},
        {text="Серебряная руда",ratio=3,raw_name={"tile.thermalfoundation.ore.silver.name"},fingerprint={{dmg=66.0,id="ThermalFoundation:material"},{dmg=6.0,id="IC2:itemIngot"}}},
        {text="Осмиевая руда",ratio=3,raw_name={"tile.oreblock.osmiumore"},fingerprint={{dmg=1.0,id="Mekanism:Ingot"}}},
        {text="Свинцовая руда",ratio=3,raw_name={"tile.thermalfoundation.ore.lead.name","ic2.blockorelead"},fingerprint={{dmg=67.0,id="ThermalFoundation:material"},{dmg=5.0,id="IC2:itemIngot"}}}
    },

    food = {{dmg=0.0, id="minecraft:melon"}, {id="minecraft:apple",dmg=0.0}}
}
