{
    shop = {
        {text = "Деньги", sellPrice = 1, buyPrice = 1, minCount = 1, maxCount = 1024, fingerprint = {{dmg=0.0,id="customnpcs:npcMoney"}}, raw_name = {"item.npcmoney"}},
        {text = "Малахит", sellPrice = 30, minCount = 1, maxCount = 1024, fingerprint = {{dmg=0.0,id="dwcity:Malahit"}}, raw_name = {"dwcity:Malahit"}},

        --vanilla
        {text = "Алмаз", buyPrice = 0.4, minCount = 1, maxCount = 2048, fingerprint = {{dmg=0.0,id="minecraft:diamond"}}, raw_name = {"item.diamond"}},
        {text = "Уголь", buyPrice = 0.05, minCount = 1, maxCount = 2048, fingerprint = {{dmg=0.0,id="minecraft:coal"}}, raw_name = {"item.coal"}},
        {text = "Красная пыль", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:redstone",dmg=0.0}}, raw_name = {"item.redstone"}},
        {text = "Светопыль", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:glowstone_dust",dmg=0.0}}, raw_name = {"item.yellowdust"}},
        {text = "Кварц", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{dmg=0.0,id="minecraft:quartz"}}, raw_name = {"item.netherquartz"}},
        {text = "Изумруд", buyPrice = 1, minCount = 1, maxCount = 512, fingerprint = {{id="minecraft:emerald",dmg=0.0}}, raw_name = {"item.emerald"}},

        {text = "Шерсть", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:wool",dmg=0.0}}, raw_name = {"tile.cloth.white"}},
        {text = "Кость", buyPrice = 0.2, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:bone",dmg=0.0}}, raw_name = {"item.bone"}},
        {text = "Гнилая плоть", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:rotten_flesh",dmg=0.0}}, raw_name = {"item.rottenflesh"}},
        {text = "Жемчуг эндера", buyPrice = 0.4, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:ender_pearl",dmg=0.0}}, raw_name = {"item.enderpearl"}},
        {text = "Череп скелета", buyPrice = 0.2, minCount = 1, maxCount = 256, fingerprint = {{id="minecraft:skull",dmg=0.0}}, raw_name = {"item.skull.skeleton"}},
        {text = "Голова зомби", buyPrice = 0.2, minCount = 1, maxCount = 256, fingerprint = {{id="minecraft:skull",dmg=2.0}}, raw_name = {"item.skull.zombie"}},
        {text = "Череп Скелета-Иссушителя", buyPrice = 30, minCount = 1, needed = 128, maxCount = 128, fingerprint = {{dmg=1.0,id="minecraft:skull"}}, raw_name = {"item.skull.wither"}},
        {text = "Перо", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{dmg=0.0,id="minecraft:feather"}}, raw_name = {"item.feather"}},
        {text = "Стержень ифрита", buyPrice = 0.5, minCount = 1, maxCount = 512, fingerprint = {{id="minecraft:blaze_rod",dmg=0.0}}, raw_name = {"item.blazerod"}},
        {text = "Сгусток слизи", buyPrice = 0.5, minCount = 1, maxCount = 512, fingerprint = {{id="minecraft:slime_ball",dmg=0.0}}, raw_name = {"item.slimeball"}},
        {text = "Слеза Гаста", buyPrice = 0.4, minCount = 1, maxCount = 512, fingerprint = {{id="minecraft:ghast_tear",dmg=0.0}}, raw_name = {"item.ghasttear"}},
        {text = "Адская звезда", buyPrice = 100, minCount = 1, maxCount = 32, fingerprint = {{id="minecraft:nether_star",dmg=0.0}}, raw_name = {"item.netherstar"}},
        {text = "Кожа", buyPrice = 0.2, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:leather",dmg=0.0}}, raw_name = {"item.leather"}},
        {text = "Обсидиан", buyPrice = 0.05, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:obsidian",dmg=0.0}}, raw_name = {"tile.obsidian"}},
        {text = "Сырая рыба", buyPrice = 0.1, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:fish",dmg=0.0}}, raw_name = {"item.fish.cod.raw"}},
        {text = "Яйцо", buyPrice = 0.1, minCount = 1, maxCount = 1024, fingerprint = {{id="minecraft:egg",dmg=0.0}}, raw_name = {"item.egg"}},
        {text = "Сахарный тростник", buyPrice = 0.01, minCount = 1, maxCount = 2048, fingerprint = {{id="minecraft:reeds",dmg=0.0}}, raw_name = {"item.reeds"}},

        --ae2
        {text = "Кристалл истинного кварца", buyPrice = 0.2, minCount = 1, maxCount = 2048, fingerprint = {{dmg=0.0,id="appliedenergistics2:item.ItemMultiMaterial"}}, raw_name = {"item.appliedenergistics2.itemmaterial.certusquartzcrystal"}},
        {text = "Зар. кристалл ист. кварца", buyPrice = 0.5, minCount = 1, maxCount = 2048, fingerprint = {{dmg=1.0,id="appliedenergistics2:item.ItemMultiMaterial"}}, raw_name = {"item.appliedenergistics2.itemmaterial.certusquartzcrystalcharged"}},
        {text = "Вычислительный пресс", buyPrice = 17, minCount = 1, maxCount = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=13.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.calcprocessorpress"}},
        {text = "Инженерный пресс", buyPrice = 17, minCount = 1, maxCount = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=14.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.engprocessorpress"}},
        {text = "Логический пресс", buyPrice = 17, minCount = 1, maxCount = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=15.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.logicprocessorpress"}},
        {text = "Кремниевый пресс", buyPrice = 17, minCount = 1, maxCount = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=19.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.siliconpress"}},
        {text = "Сингулярность", buyPrice = 2, minCount = 1, maxCount = 2, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=47.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.singularity"}},
        {text = "Небесный камень", buyPrice = 0.15, minCount = 1, maxCount = 2048, fingerprint = {{id="appliedenergistics2:tile.BlockSkyStone",dmg=0.0}}, raw_name = {"tile.appliedenergistics2.blockskystone"}},
        {text = "Логический процессор", buyPrice = 0.15, minCount = 1, maxCount = 512, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=22.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.logicprocessor"}},
        {text = "Инженерный процессор", buyPrice = 0.45, minCount = 1, maxCount = 512, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=24.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.engprocessor"}},
        {text = "Вычислительный процессор", buyPrice = 0.25, minCount = 1, maxCount = 512, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=23.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.calcprocessor"}},

        --ic2
        {text = "Резина", buyPrice = 0.01, minCount = 1, maxCount = 1024, fingerprint = {{dmg=0.0,id="IC2:itemRubber"}}, raw_name = {"ic2.itemrubber"}},
        {text = "Углепластик", buyPrice = 0.5, minCount = 1, maxCount = 128, fingerprint = {{dmg=0.0,id="IC2:itemPartCarbonPlate"}}, raw_name = {"ic2.itempartcarbonplate"}},
        {text = "Слиток закаленного железа", buyPrice = 0.3, minCount = 1, maxCount = 128, fingerprint = {{dmg=3.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingotadviron"}},
        {text = "Оловянный слиток", buyPrice = 0.1, minCount = 1, maxCount = 1024, fingerprint = {{dmg=1.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingottin"}},
        {text = "Серебрянный слиток", buyPrice = 0.1, minCount = 1, maxCount = 1024, fingerprint = {{dmg=6.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingotsilver"}},
        {text = "Свинцовый слиток", buyPrice = 0.1, minCount = 1, maxCount = 1024, fingerprint = {{dmg=5.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingotlead"}},
        {text = "Уран 238", buyPrice = 0.2, minCount = 1, maxCount = 1024, fingerprint = {{dmg=0.0,id="IC2:itemUran238"}}, raw_name = {"ic2.itemuran238"}},
        {text = "Кусочек урана 235", buyPrice = 0.5, minCount = 1, maxCount = 512, fingerprint = {{dmg=0.0,id="IC2:itemUran235small"}}, raw_name = {"ic2.itemuran235small"}},
        {text = "Энергетический кристалл", buyPrice = 2, minCount = 1, maxCount = 16, needed = 16, ignoreDamage = true, fingerprint = {{dmg=27.0,id="IC2:itemBatCrystal"}}, raw_name = {"ic2.itembatcrystal"}},
        {text = "Лазуротроновый кристалл", buyPrice = 5, minCount = 1, maxCount = 16, needed = 16, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemBatLamaCrystal"}}, raw_name = {"ic2.itembatlamacrystal"}},
        {text = "Иридий", buyPrice = 10, minCount = 1, maxCount = 10, needed = 10, fingerprint = {{id="IC2:itemOreIridium",dmg=0.0}}, raw_name = {"ic2.itemoreiridium"}},
        {text = "Укр. иридиевая пластина", buyPrice = 40, minCount = 1, needed = 8, maxCount = 8, fingerprint = {{id="IC2:itemPartIridium",dmg=0.0}}, raw_name = {"ic2.itempartiridium"}},
        {text = "Ускоритель", buyPrice = 11, minCount = 1, needed = 32, maxCount = 32, fingerprint = {{dmg=0.0,id="IC2:upgradeModule"}}, raw_name = {"ic2.overclockerupgrade"}},
        {text = "Композит", buyPrice = 0.5, minCount = 1, maxCount = 128, needed = 128, fingerprint = {{dmg=0.0,id="IC2:itemPartAlloy"}}, raw_name = {"ic2.itempartalloy"}},
        {text = "Капсула хладагента", buyPrice = 0.5, minCount = 1, maxCount = 256, fingerprint = {{dmg=9.0,id="IC2:itemCellEmpty"}}, raw_name = {"ic2.itemcellcoolant"}},
        {text = "Углепластик", buyPrice = 0.5, minCount = 1, maxCount = 256, fingerprint = {{dmg=9.0,id="IC2:itemCellEmpty"}}, raw_name = {"ic2.itemcellcoolant"}},
        {text = "Солн. панель 1-го ур.", buyPrice = 1.5, minCount = 1, maxCount = 2048, fingerprint = {{dmg=3.0,id="IC2:blockGenerator"}}, raw_name = {"ic2.blocksolargenerator"}},
        {text = "Солн. панель 2-го ур.", buyPrice = 12, minCount = 1, maxCount = 512, fingerprint = {{dmg=0.0,id="CompactSolar:CompactSolarBlock"}}, raw_name = {"tile.compactsolars.lv_block"}},
        {text = "Солн. панель 3-го ур.", buyPrice = 100, minCount = 1, maxCount = 64, fingerprint = {{dmg=1.0,id="CompactSolar:CompactSolarBlock"}}, raw_name = {"tile.compactsolars.mv_block"}},
        {text = "Солн. панель 4-го ур.", buyPrice = 800, minCount = 1, maxCount = 4, fingerprint = {{dmg=2.0,id="CompactSolar:CompactSolarBlock"}}, raw_name = {"tile.compactsolars.hv_block"}},
        {text = "Сверхпроводник", buyPrice = 55, minCount = 1, maxCount = 6, fingerprint = {{dmg=1.0,id="GraviSuite:itemSimpleItem"}}, raw_name = {"item.superconductor"}},

        {text = "Нано-сабля", buyPrice = 1500, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=1.0,id="IC2:itemNanoSaber"}}, raw_name = {"ic2.itemnanosaber"}},
        {text = "Нано-шлем", buyPrice = 2000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=0.0,id="IC2:itemArmorNanoHelmet"}}, raw_name = {"ic2.itemarmornanohelmet"}},
        {text = "Нано-поножи", buyPrice = 1500, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorNanoLegs"}}, raw_name = {"ic2.itemarmornanolegs"}},
        {text = "Нано-ботинки", buyPrice = 1500, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorNanoBoots"}}, raw_name = {"ic2.itemarmornanoboots"}},
        {text = "Квантовый шлем", buyPrice = 17000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumHelmet"}}, raw_name = {"ic2.itemarmorquantumhelmet"}},
        {text = "Квантовая кираса", buyPrice = 15000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumChestplate"}}, raw_name = {"ic2.itemarmorquantumchestplate"}},
        {text = "Квантовые поножи", buyPrice = 15000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumLegs"}}, raw_name = {"ic2.itemarmorquantumlegs"}},
        {text = "Квантовые ботинки", buyPrice = 15000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumBoots"}}, raw_name = {"ic2.itemarmorquantumboots"}},
        {text = "Улучшенный наножилет", buyPrice = 16000, minCount = 0, maxCount = 512, ignoreDamage = true, fingerprint = {{dmg=26.0,id="GraviSuite:advNanoChestPlate"}}, raw_name = {"item.advnanochestplate"}},

        --thaumcraft
        {text = "Семя пустоты", buyPrice = 0.1, minCount = 1, maxCount = 16, fingerprint = {{dmg=17.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.17"}},
        {text = "Фрагмент знаний", buyPrice = 0.1, minCount = 1, maxCount = 1024, fingerprint = {{id="Thaumcraft:ItemResource",dmg=9.0}}, raw_name = {"item.itemresource.9"}},
        {text = "Нитор", buyPrice = 0.1, minCount = 1, maxCount = 32, fingerprint = {{dmg=1.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.1"}},
        {text = "Грозовой кристалл", buyPrice = 0.05, minCount = 1, maxCount = 128, fingerprint = {{dmg=0.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.0"}},
        {text = "Огненный кристалл", buyPrice = 0.05, minCount = 1, maxCount = 128, fingerprint = {{dmg=1.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.1"}},
        {text = "Ледяной кристалл", buyPrice = 0.05, minCount = 1, maxCount = 128, fingerprint = {{dmg=2.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.2"}},
        {text = "Земляной кристалл", buyPrice = 0.05, minCount = 1, maxCount = 128, fingerprint = {{dmg=3.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.3"}},
        {text = "Кристалл порядка", buyPrice = 0.05, minCount = 1, maxCount = 128, fingerprint = {{dmg=4.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.4"}},
        {text = "Энтропийный кристалл", buyPrice = 0.05, minCount = 1, maxCount = 128, fingerprint = {{dmg=5.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.5"}},
        {text = "Сбалансированный кристалл", buyPrice = 0.3, minCount = 1, maxCount = 128, fingerprint = {{dmg=6.0,id="Thaumcraft:ItemShard"}}, raw_name = {"item.itemshard.6"}},
        {text = "Ихор", buyPrice = 12, minCount = 1, maxCount = 32, fingerprint = {{dmg=0.0,id="ThaumicTinkerer:kamiResource"}}, raw_name = {"item.kamiresource"}},
        {text = "Зараженное щупальце", buyPrice = 0.4, minCount = 1, maxCount = 1024, fingerprint = {{dmg=12.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.12"}},
        {text = "Зараженная слизь", buyPrice = 0.4, minCount = 1, maxCount = 512, fingerprint = {{dmg=11.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.11"}},
        {text = "Мозг зомби", buyPrice = 0.2, minCount = 1, maxCount = 512, fingerprint = {{dmg=0.0,id="Thaumcraft:ItemZombieBrain"}}, raw_name = {"item.itemzombiebrain"}},
        {text = "Кристалл края", buyPrice = 2, minCount = 1, maxCount = 32, fingerprint = {{dmg=7.0,id="ThaumicTinkerer:kamiResource"}}, raw_name = {"item.kamiresource"}},
        {text = "Кристалл нижнего мира", buyPrice = 2, minCount = 1, maxCount = 32, fingerprint = {{dmg=6.0,id="ThaumicTinkerer:kamiResource"}}, raw_name = {"item.kamiresource"}},
        {text = "Эфирная эссенция", buyPrice = 0.4, minCount = 1, maxCount = 512, fingerprint = {{dmg=0.0,id="Thaumcraft:ItemWispEssence"}}, raw_name = {"item.itemwispessence"}},
        {text = "Фрагмент знаний", buyPrice = 0.1, minCount = 1, maxCount = 1024, fingerprint = {{dmg=9.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.9"}},
        {text = "Ртуть", buyPrice = 0.1, minCount = 1, maxCount = 1024, fingerprint = {{dmg=3.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.3"}},
        {text = "Алюментум", buyPrice = 0.1, minCount = 1, maxCount = 32, fingerprint = {{dmg=0.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.0"}},

        --forestry
        {text = "Скопление пыльцы", buyPrice = 0.02, minCount = 1, maxCount = 512, fingerprint = {{id="Forestry:pollen",dmg=0.0}}, raw_name = {"item.for.pollen.normal"}},
        {text = "Маточное молочко", buyPrice = 0.02, minCount = 1, maxCount = 512, fingerprint = {{id="Forestry:royalJelly",dmg=0.0}}, raw_name = {"item.for.royaljelly"}},
        {text = "Пропитанный корпус", buyPrice = 0.6, minCount = 1, maxCount = 512, fingerprint = {{id="Forestry:impregnatedCasing",dmg=0.0}}, raw_name = {"item.for.impregnatedcasing"}},
        {text = "Пропитанная обшивка", buyPrice = 0.3, minCount = 1, maxCount = 1024, fingerprint = {{id="Forestry:craftingMaterial",dmg=6.0}}, raw_name = {"item.for.craftingmaterial.scentedpaneling"}},
        {text = "Капля меда", buyPrice = 0.01, minCount = 1, maxCount = 2048, fingerprint = {{id="Forestry:honeyDrop",dmg=0.0}}, raw_name = {"item.for.honeydrop.honey"}},
        {text = "Фермент", buyPrice = 0.5, minCount = 1, maxCount = 64, fingerprint = {{id="Genetics:misc",dmg=3.0}}, raw_name = {"item.misc"}},
        {text = "Необычная пыльца", buyPrice = 0.1, minCount = 1, maxCount = 512, fingerprint = {{id="MagicBees:pollen",dmg=0.0}}, raw_name = {"item.pollen"}},
        {text = "Зачарованная капля", buyPrice = 0.1, minCount = 1, maxCount = 512, fingerprint = {{id="MagicBees:drop",dmg=0.0}}, raw_name = {"item.drop"}},
        {text = "Магический воск", buyPrice = 0.02, minCount = 1, maxCount = 512, fingerprint = {{id="MagicBees:wax",dmg=0.0}}, raw_name = {"item.wax"}},
        {text = "Пчелиный воск", buyPrice = 0.01, minCount = 1, maxCount = 512, fingerprint = {{id="Forestry:beeswax",dmg=0.0}}, raw_name = {"item.for.beeswax"}},
        {text = "Бронзовый слиток", buyPrice = 0.3, minCount = 1, maxCount = 512, fingerprint = {{id="Forestry:ingotBronze",dmg=0.0}}, raw_name = {"item.for.ingotbronze"}},

        --thermal
        {text = "Синаловый слиток", buyPrice = 1, minCount = 1, maxCount = 32, fingerprint = {{dmg=74.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotsignalum"}},
        {text = "Слиток эндериума", buyPrice = 2, minCount = 1, maxCount = 32, fingerprint = {{dmg=76.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotenderium"}},
        {text = "Ламиумовый слиток", buyPrice = 1, minCount = 1, maxCount = 32, fingerprint = {{dmg=75.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotlumium"}},
        {text = "Платиновый слиток", buyPrice = 1, minCount = 1, maxCount = 64, fingerprint = {{dmg=69.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotplatinum"}},
        {text = "Никелевый слиток", buyPrice = 0.1, minCount = 1, maxCount = 64, fingerprint = {{dmg=68.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotnickel"}},
        {text = "Электрумовый слиток", buyPrice = 0.3, minCount = 1, maxCount = 128, fingerprint = {{dmg=71.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotelectrum"}},
        {text = "Обогащенный шлак", buyPrice = 0.2, minCount = 1, maxCount = 512, fingerprint = {{dmg=515.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.slagrich"}},

        --dwcity
        {text = "Флаксовый слиток", buyPrice = 1.1, minCount = 1, maxCount = 32, ignoreDamage = true, fingerprint = {{dmg=32.0,id="dwcity:Flux_ingot"}}, raw_name = {"item.redstonearsenal.material.ingotelectrumflux"}},
        {text = "Дракониевый кристалл", buyPrice = 7, minCount = 1, maxCount = 32, fingerprint = {{dmg=0.0,id="dwcity:Dragon_shard"}}, raw_name = {"item.dragon_shard"}},
        {text = "Ториевый слиток", buyPrice = 0.3, minCount = 1, maxCount = 256, fingerprint = {{dmg=0.0,id="dwcity:Thorium_ingot"}}, raw_name = {"item.thorium_ingot"}},
        {text = "Трижды сжатый камень", buyPrice = 10, minCount = 1, maxCount = 16, fingerprint = {{dmg=0.0,id="dwcity:Powder11"}}, raw_name = {"item.powder11"}},
        {text = "Темная материя", buyPrice = 2.5, minCount = 1, maxCount = 64, fingerprint = {{dmg=0.0,id="dwcity:Dark_materia"}}, raw_name = {"item.dark_materia"}},
        {text = "Ледяная материя", buyPrice = 2.5, minCount = 1, maxCount = 64, fingerprint = {{dmg=0.0,id="dwcity:Sky_materia"}}, raw_name = {"item.sky_materia"}},
        {text = "Вис материя", buyPrice = 2.5, minCount = 1, maxCount = 64, fingerprint = {{dmg=0.0,id="dwcity:Vis_materia"}}, raw_name = {"item.vis_materia"}},
        {text = "Живая материя", buyPrice = 2.5, minCount = 1, maxCount = 64, fingerprint = {{dmg=0.0,id="dwcity:Live_materia"}}, raw_name = {"item.live_materia"}},
        {text = "Солнечная материя", buyPrice = 2.5, minCount = 1, maxCount = 64, fingerprint = {{dmg=0.0,id="dwcity:Fire_materia"}}, raw_name = {"item.fire_materia"}},

        --draconic
        {text = "Дракониевый слиток", buyPrice = 2, minCount = 1, maxCount = 256, fingerprint = {{dmg=0.0,id="DraconicEvolution:draconiumIngot"}}, raw_name = {"item.draconicevolution:draconiumingot"}},
        {text = "Пробужденный дк слиток", buyPrice = 20, minCount = 1, maxCount = 16, fingerprint = {{dmg=0.0,id="DraconicEvolution:draconicIngot"}}, raw_name = {"item.draconicevolution:draconicingot"}},
        {text = "Дракониевая пыль", buyPrice = 0.4, minCount = 1, maxCount = 512, fingerprint = {{dmg=0.0,id="DraconicEvolution:draconiumDust"}}, raw_name = {"item.draconicevolution:draconiumdust"}},

        --botania

    },

    ore = {
        {text="Железная руда",ratio=2.33,raw_name={"tile.oreiron"},fingerprint={{dmg=0.0,id="minecraft:iron_ingot"}}},
        {text="Золотая руда",ratio=2.33,raw_name={"tile.oregold"},fingerprint={{dmg=0.0,id="minecraft:gold_ingot"}}},
        {text="Медная руда",ratio=2.33,raw_name={"tile.thermalfoundation.ore.copper.name","ic2.blockorecopper"},fingerprint={{dmg=64.0,id="ThermalFoundation:material"},{dmg=0.0,id="IC2:itemIngot"},{dmg=0.0,id="ImmersiveEngineering:metal"},{dmg=5.0,id="Mekanism:Ingot"}}},
        {text="Оловянная руда",ratio=2.33,raw_name={"tile.thermalfoundation.ore.tin.name","ic2.blockoretin"},fingerprint={{dmg=6.0,id="Mekanism:Ingot"},{dmg=65.0,id="ThermalFoundation:material"},{dmg=1.0,id="IC2:itemIngot"}}},
        {text="Серебряная руда",ratio=2.33,raw_name={"tile.thermalfoundation.ore.silver.name"},fingerprint={{dmg=66.0,id="ThermalFoundation:material"},{dmg=6.0,id="IC2:itemIngot"}}},
        {text="Осмиевая руда",ratio=2.33,raw_name={"tile.oreblock.osmiumore"},fingerprint={{dmg=1.0,id="Mekanism:Ingot"}}},
        {text="Свинцовая руда",ratio=2.33,raw_name={"tile.thermalfoundation.ore.lead.name","ic2.blockorelead"},fingerprint={{dmg=67.0,id="ThermalFoundation:material"},{dmg=5.0,id="IC2:itemIngot"}}}
    },

    food = {{dmg=0.0, id="minecraft:cooked_beef"}}
}
